<?php
/**
 * ApparelStyle
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ApparelStyle Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApparelStyle
{
    /**
     * Possible values of this enum
     */
    public const UNISEX = 'Unisex';

    public const YOUTH = 'Youth';

    public const GIRLS = 'Girls';

    public const BOYS = 'Boys';

    public const WOMENS = 'Womens';

    public const WOMENS_TALL = 'WomensTall';

    public const MENS = 'Mens';

    public const MENS_TALL = 'MensTall';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNISEX,
            self::YOUTH,
            self::GIRLS,
            self::BOYS,
            self::WOMENS,
            self::WOMENS_TALL,
            self::MENS,
            self::MENS_TALL
        ];
    }
}


