<?php
/**
 * CombinedPart
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CombinedPart Class Doc Comment
 *
 * @category Class
 * @description Extended Part with combined pricing.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CombinedPart implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CombinedPart';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'part_id' => 'string',
        'part_description' => 'string',
        'part_price_array' => '\OpenAPI\Client\Model\CombinedPartPriceArray',
        'part_group' => 'int',
        'next_part_group' => 'int',
        'part_group_required' => 'bool',
        'part_group_description' => 'string',
        'ratio' => 'string',
        'default_part' => 'bool',
        'location_id_array' => '\OpenAPI\Client\Model\LocationIdArray'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'part_id' => null,
        'part_description' => null,
        'part_price_array' => null,
        'part_group' => null,
        'next_part_group' => null,
        'part_group_required' => null,
        'part_group_description' => null,
        'ratio' => null,
        'default_part' => null,
        'location_id_array' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'part_id' => false,
        'part_description' => true,
        'part_price_array' => true,
        'part_group' => false,
        'next_part_group' => true,
        'part_group_required' => false,
        'part_group_description' => true,
        'ratio' => false,
        'default_part' => true,
        'location_id_array' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'part_id' => 'partId',
        'part_description' => 'partDescription',
        'part_price_array' => 'PartPriceArray',
        'part_group' => 'partGroup',
        'next_part_group' => 'nextPartGroup',
        'part_group_required' => 'partGroupRequired',
        'part_group_description' => 'partGroupDescription',
        'ratio' => 'ratio',
        'default_part' => 'defaultPart',
        'location_id_array' => 'LocationIdArray'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'part_id' => 'setPartId',
        'part_description' => 'setPartDescription',
        'part_price_array' => 'setPartPriceArray',
        'part_group' => 'setPartGroup',
        'next_part_group' => 'setNextPartGroup',
        'part_group_required' => 'setPartGroupRequired',
        'part_group_description' => 'setPartGroupDescription',
        'ratio' => 'setRatio',
        'default_part' => 'setDefaultPart',
        'location_id_array' => 'setLocationIdArray'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'part_id' => 'getPartId',
        'part_description' => 'getPartDescription',
        'part_price_array' => 'getPartPriceArray',
        'part_group' => 'getPartGroup',
        'next_part_group' => 'getNextPartGroup',
        'part_group_required' => 'getPartGroupRequired',
        'part_group_description' => 'getPartGroupDescription',
        'ratio' => 'getRatio',
        'default_part' => 'getDefaultPart',
        'location_id_array' => 'getLocationIdArray'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('part_id', $data ?? [], null);
        $this->setIfExists('part_description', $data ?? [], null);
        $this->setIfExists('part_price_array', $data ?? [], null);
        $this->setIfExists('part_group', $data ?? [], null);
        $this->setIfExists('next_part_group', $data ?? [], null);
        $this->setIfExists('part_group_required', $data ?? [], null);
        $this->setIfExists('part_group_description', $data ?? [], null);
        $this->setIfExists('ratio', $data ?? [], null);
        $this->setIfExists('default_part', $data ?? [], null);
        $this->setIfExists('location_id_array', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['part_id'] === null) {
            $invalidProperties[] = "'part_id' can't be null";
        }
        if ($this->container['part_description'] === null) {
            $invalidProperties[] = "'part_description' can't be null";
        }
        if ($this->container['part_price_array'] === null) {
            $invalidProperties[] = "'part_price_array' can't be null";
        }
        if ($this->container['part_group'] === null) {
            $invalidProperties[] = "'part_group' can't be null";
        }
        if ($this->container['part_group_required'] === null) {
            $invalidProperties[] = "'part_group_required' can't be null";
        }
        if ($this->container['part_group_description'] === null) {
            $invalidProperties[] = "'part_group_description' can't be null";
        }
        if ($this->container['ratio'] === null) {
            $invalidProperties[] = "'ratio' can't be null";
        }
        if (!preg_match("/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/", $this->container['ratio'])) {
            $invalidProperties[] = "invalid value for 'ratio', must be conform to the pattern /^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/.";
        }

        if ($this->container['default_part'] === null) {
            $invalidProperties[] = "'default_part' can't be null";
        }
        if ($this->container['location_id_array'] === null) {
            $invalidProperties[] = "'location_id_array' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets part_id
     *
     * @return string
     */
    public function getPartId()
    {
        return $this->container['part_id'];
    }

    /**
     * Sets part_id
     *
     * @param string $part_id part_id
     *
     * @return self
     */
    public function setPartId($part_id)
    {
        if (is_null($part_id)) {
            throw new \InvalidArgumentException('non-nullable part_id cannot be null');
        }
        $this->container['part_id'] = $part_id;

        return $this;
    }

    /**
     * Gets part_description
     *
     * @return string
     */
    public function getPartDescription()
    {
        return $this->container['part_description'];
    }

    /**
     * Sets part_description
     *
     * @param string $part_description part_description
     *
     * @return self
     */
    public function setPartDescription($part_description)
    {
        if (is_null($part_description)) {
            array_push($this->openAPINullablesSetToNull, 'part_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['part_description'] = $part_description;

        return $this;
    }

    /**
     * Gets part_price_array
     *
     * @return \OpenAPI\Client\Model\CombinedPartPriceArray
     */
    public function getPartPriceArray()
    {
        return $this->container['part_price_array'];
    }

    /**
     * Sets part_price_array
     *
     * @param \OpenAPI\Client\Model\CombinedPartPriceArray $part_price_array part_price_array
     *
     * @return self
     */
    public function setPartPriceArray($part_price_array)
    {
        if (is_null($part_price_array)) {
            array_push($this->openAPINullablesSetToNull, 'part_price_array');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_price_array', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['part_price_array'] = $part_price_array;

        return $this;
    }

    /**
     * Gets part_group
     *
     * @return int
     */
    public function getPartGroup()
    {
        return $this->container['part_group'];
    }

    /**
     * Sets part_group
     *
     * @param int $part_group A numeric identifier grouping mutually exclusive parts together. When configuring data, always start with part group “1”
     *
     * @return self
     */
    public function setPartGroup($part_group)
    {
        if (is_null($part_group)) {
            throw new \InvalidArgumentException('non-nullable part_group cannot be null');
        }
        $this->container['part_group'] = $part_group;

        return $this;
    }

    /**
     * Gets next_part_group
     *
     * @return int|null
     */
    public function getNextPartGroup()
    {
        return $this->container['next_part_group'];
    }

    /**
     * Sets next_part_group
     *
     * @param int|null $next_part_group next_part_group
     *
     * @return self
     */
    public function setNextPartGroup($next_part_group)
    {
        if (is_null($next_part_group)) {
            array_push($this->openAPINullablesSetToNull, 'next_part_group');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('next_part_group', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['next_part_group'] = $next_part_group;

        return $this;
    }

    /**
     * Gets part_group_required
     *
     * @return bool
     */
    public function getPartGroupRequired()
    {
        return $this->container['part_group_required'];
    }

    /**
     * Sets part_group_required
     *
     * @param bool $part_group_required A boolean value specifying if this partGroup is required for the product configuration. If set to TRUE, a selection in the partGroup is required for ordering
     *
     * @return self
     */
    public function setPartGroupRequired($part_group_required)
    {
        if (is_null($part_group_required)) {
            throw new \InvalidArgumentException('non-nullable part_group_required cannot be null');
        }
        $this->container['part_group_required'] = $part_group_required;

        return $this;
    }

    /**
     * Gets part_group_description
     *
     * @return string
     */
    public function getPartGroupDescription()
    {
        return $this->container['part_group_description'];
    }

    /**
     * Sets part_group_description
     *
     * @param string $part_group_description part_group_description
     *
     * @return self
     */
    public function setPartGroupDescription($part_group_description)
    {
        if (is_null($part_group_description)) {
            array_push($this->openAPINullablesSetToNull, 'part_group_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_group_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['part_group_description'] = $part_group_description;

        return $this;
    }

    /**
     * Gets ratio
     *
     * @return string
     */
    public function getRatio()
    {
        return $this->container['ratio'];
    }

    /**
     * Sets ratio
     *
     * @param string $ratio Describes how the amount of partIds that need to be added to the order based on the number of products ordered
     *
     * @return self
     */
    public function setRatio($ratio)
    {
        if (is_null($ratio)) {
            throw new \InvalidArgumentException('non-nullable ratio cannot be null');
        }

        if ((!preg_match("/^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/", ObjectSerializer::toString($ratio)))) {
            throw new \InvalidArgumentException("invalid value for \$ratio when calling CombinedPart., must conform to the pattern /^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$/.");
        }

        $this->container['ratio'] = $ratio;

        return $this;
    }

    /**
     * Gets default_part
     *
     * @return bool
     */
    public function getDefaultPart()
    {
        return $this->container['default_part'];
    }

    /**
     * Sets default_part
     *
     * @param bool $default_part default_part
     *
     * @return self
     */
    public function setDefaultPart($default_part)
    {
        if (is_null($default_part)) {
            array_push($this->openAPINullablesSetToNull, 'default_part');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_part', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_part'] = $default_part;

        return $this;
    }

    /**
     * Gets location_id_array
     *
     * @return \OpenAPI\Client\Model\LocationIdArray
     */
    public function getLocationIdArray()
    {
        return $this->container['location_id_array'];
    }

    /**
     * Sets location_id_array
     *
     * @param \OpenAPI\Client\Model\LocationIdArray $location_id_array location_id_array
     *
     * @return self
     */
    public function setLocationIdArray($location_id_array)
    {
        if (is_null($location_id_array)) {
            array_push($this->openAPINullablesSetToNull, 'location_id_array');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('location_id_array', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['location_id_array'] = $location_id_array;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


