<?php
/**
 * DecorationGeometryType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DecorationGeometryType Class Doc Comment
 *
 * @category Class
 * @description Decoration Geometry Types
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DecorationGeometryType
{
    /**
     * Possible values of this enum
     */
    public const CIRCLE = 'Circle';

    public const RECTANGLE = 'Rectangle';

    public const OTHER = 'Other';

    public const NOT_AVAILABLE = 'Not available';

    public const IRREGULAR = 'Irregular';

    public const SQUARE = 'Square';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CIRCLE,
            self::RECTANGLE,
            self::OTHER,
            self::NOT_AVAILABLE,
            self::IRREGULAR,
            self::SQUARE
        ];
    }
}


