<?php
/**
 * INVCQueryType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * INVCQueryType Class Doc Comment
 *
 * @category Class
 * @description The type of query to perform for GetInvoices
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class INVCQueryType
{
    /**
     * Possible values of this enum
     */
    public const PO_NUMBER = 'PO_NUMBER';

    public const INVOICE_NUMBER = 'INVOICE_NUMBER';

    public const DATE = 'DATE';

    public const AVAILABLE_DATE_TIME = 'AVAILABLE_DATE_TIME';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PO_NUMBER,
            self::INVOICE_NUMBER,
            self::DATE,
            self::AVAILABLE_DATE_TIME
        ];
    }
}


