<?php
/**
 * InvoiceLineItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InvoiceLineItem Class Doc Comment
 *
 * @category Class
 * @description Field       Description     Data Type       Required invoiceLineItemNumber       The line item number of the line item   DOUBLE  FALSE productId   The productId when the line item applies to a product.  64 STRING       FALSE partId      The partId when the line item applies to a product.     64 STRING       FALSE chargeId    The chargeId when the line item applies to a charge.    64 STRING       TRUE purchaseOrderLineItemNumber The line item number of the purchase order that the invoice references  64 STRING       FALSE # noqa orderedQuantity     The quantity ordered by the referenced purchase order   DOUBLE  FALSE invoiceQuantity     The quantity of the line item invoiced. DOUBLE  TRUE backOrderedQuantity The quantity of the line item backordered.      DOUBLE  FALSE quantityUOM The unit of measure of the orderQuantity, invoicedQuantity, and backOrderedQuantity     2 STRING FACIT  TRUE # noqa lineItemDescription A textual description of the line item  1024 STRING     TRUE unitPrice   The price of the unit in the currency of the purchase order     DOUBLE  TRUE discountAmount      An amount of discount applied to the item.      DOUBLE  FALSE extendedPrice       \&quot;The extended price for the line item  Note: extendedPrice &#x3D; (unitPrice * invoicedQuantity) - discountAmount\&quot;      DOUBLE  TRUE distributorProductId        The distributor’s productId for the item when the line item applies to a product.       64 STRING       FALSE  # noqa distributorPartId   The distributor’s partId for the item when the line item applies to a product.  64 STRING       FALSE  # noqa
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InvoiceLineItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InvoiceLineItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'invoice_line_item_number' => 'float',
        'product_id' => 'string',
        'part_id' => 'string',
        'charge_id' => 'string',
        'purchase_order_line_item_number' => 'string',
        'ordered_quantity' => 'float',
        'invoice_quantity' => 'float',
        'back_ordered_quantity' => 'float',
        'quantity_uom' => 'string',
        'line_item_description' => 'string',
        'unit_price' => 'float',
        'discount_amount' => 'float',
        'extended_price' => 'float',
        'distributor_product_id' => 'string',
        'distributor_part_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'invoice_line_item_number' => null,
        'product_id' => null,
        'part_id' => null,
        'charge_id' => null,
        'purchase_order_line_item_number' => null,
        'ordered_quantity' => null,
        'invoice_quantity' => null,
        'back_ordered_quantity' => null,
        'quantity_uom' => null,
        'line_item_description' => null,
        'unit_price' => null,
        'discount_amount' => null,
        'extended_price' => null,
        'distributor_product_id' => null,
        'distributor_part_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'invoice_line_item_number' => true,
        'product_id' => true,
        'part_id' => true,
        'charge_id' => false,
        'purchase_order_line_item_number' => true,
        'ordered_quantity' => true,
        'invoice_quantity' => false,
        'back_ordered_quantity' => true,
        'quantity_uom' => false,
        'line_item_description' => false,
        'unit_price' => false,
        'discount_amount' => true,
        'extended_price' => false,
        'distributor_product_id' => true,
        'distributor_part_id' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'invoice_line_item_number' => 'invoiceLineItemNumber',
        'product_id' => 'productId',
        'part_id' => 'partId',
        'charge_id' => 'chargeId',
        'purchase_order_line_item_number' => 'purchaseOrderLineItemNumber',
        'ordered_quantity' => 'orderedQuantity',
        'invoice_quantity' => 'invoiceQuantity',
        'back_ordered_quantity' => 'backOrderedQuantity',
        'quantity_uom' => 'quantityUOM',
        'line_item_description' => 'lineItemDescription',
        'unit_price' => 'unitPrice',
        'discount_amount' => 'discountAmount',
        'extended_price' => 'extendedPrice',
        'distributor_product_id' => 'distributorProductId',
        'distributor_part_id' => 'distributorPartId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'invoice_line_item_number' => 'setInvoiceLineItemNumber',
        'product_id' => 'setProductId',
        'part_id' => 'setPartId',
        'charge_id' => 'setChargeId',
        'purchase_order_line_item_number' => 'setPurchaseOrderLineItemNumber',
        'ordered_quantity' => 'setOrderedQuantity',
        'invoice_quantity' => 'setInvoiceQuantity',
        'back_ordered_quantity' => 'setBackOrderedQuantity',
        'quantity_uom' => 'setQuantityUom',
        'line_item_description' => 'setLineItemDescription',
        'unit_price' => 'setUnitPrice',
        'discount_amount' => 'setDiscountAmount',
        'extended_price' => 'setExtendedPrice',
        'distributor_product_id' => 'setDistributorProductId',
        'distributor_part_id' => 'setDistributorPartId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'invoice_line_item_number' => 'getInvoiceLineItemNumber',
        'product_id' => 'getProductId',
        'part_id' => 'getPartId',
        'charge_id' => 'getChargeId',
        'purchase_order_line_item_number' => 'getPurchaseOrderLineItemNumber',
        'ordered_quantity' => 'getOrderedQuantity',
        'invoice_quantity' => 'getInvoiceQuantity',
        'back_ordered_quantity' => 'getBackOrderedQuantity',
        'quantity_uom' => 'getQuantityUom',
        'line_item_description' => 'getLineItemDescription',
        'unit_price' => 'getUnitPrice',
        'discount_amount' => 'getDiscountAmount',
        'extended_price' => 'getExtendedPrice',
        'distributor_product_id' => 'getDistributorProductId',
        'distributor_part_id' => 'getDistributorPartId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('invoice_line_item_number', $data ?? [], null);
        $this->setIfExists('product_id', $data ?? [], null);
        $this->setIfExists('part_id', $data ?? [], null);
        $this->setIfExists('charge_id', $data ?? [], null);
        $this->setIfExists('purchase_order_line_item_number', $data ?? [], null);
        $this->setIfExists('ordered_quantity', $data ?? [], null);
        $this->setIfExists('invoice_quantity', $data ?? [], null);
        $this->setIfExists('back_ordered_quantity', $data ?? [], null);
        $this->setIfExists('quantity_uom', $data ?? [], null);
        $this->setIfExists('line_item_description', $data ?? [], null);
        $this->setIfExists('unit_price', $data ?? [], null);
        $this->setIfExists('discount_amount', $data ?? [], null);
        $this->setIfExists('extended_price', $data ?? [], null);
        $this->setIfExists('distributor_product_id', $data ?? [], null);
        $this->setIfExists('distributor_part_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['invoice_line_item_number'] === null) {
            $invalidProperties[] = "'invoice_line_item_number' can't be null";
        }
        if ($this->container['product_id'] === null) {
            $invalidProperties[] = "'product_id' can't be null";
        }
        if ($this->container['part_id'] === null) {
            $invalidProperties[] = "'part_id' can't be null";
        }
        if ($this->container['charge_id'] === null) {
            $invalidProperties[] = "'charge_id' can't be null";
        }
        if ($this->container['purchase_order_line_item_number'] === null) {
            $invalidProperties[] = "'purchase_order_line_item_number' can't be null";
        }
        if ($this->container['ordered_quantity'] === null) {
            $invalidProperties[] = "'ordered_quantity' can't be null";
        }
        if ($this->container['invoice_quantity'] === null) {
            $invalidProperties[] = "'invoice_quantity' can't be null";
        }
        if ($this->container['back_ordered_quantity'] === null) {
            $invalidProperties[] = "'back_ordered_quantity' can't be null";
        }
        if ($this->container['quantity_uom'] === null) {
            $invalidProperties[] = "'quantity_uom' can't be null";
        }
        if ($this->container['line_item_description'] === null) {
            $invalidProperties[] = "'line_item_description' can't be null";
        }
        if ($this->container['unit_price'] === null) {
            $invalidProperties[] = "'unit_price' can't be null";
        }
        if ($this->container['discount_amount'] === null) {
            $invalidProperties[] = "'discount_amount' can't be null";
        }
        if ($this->container['extended_price'] === null) {
            $invalidProperties[] = "'extended_price' can't be null";
        }
        if ($this->container['distributor_product_id'] === null) {
            $invalidProperties[] = "'distributor_product_id' can't be null";
        }
        if ($this->container['distributor_part_id'] === null) {
            $invalidProperties[] = "'distributor_part_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets invoice_line_item_number
     *
     * @return float
     */
    public function getInvoiceLineItemNumber()
    {
        return $this->container['invoice_line_item_number'];
    }

    /**
     * Sets invoice_line_item_number
     *
     * @param float $invoice_line_item_number invoice_line_item_number
     *
     * @return self
     */
    public function setInvoiceLineItemNumber($invoice_line_item_number)
    {
        if (is_null($invoice_line_item_number)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_line_item_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_line_item_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_line_item_number'] = $invoice_line_item_number;

        return $this;
    }

    /**
     * Gets product_id
     *
     * @return string
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     *
     * @param string $product_id product_id
     *
     * @return self
     */
    public function setProductId($product_id)
    {
        if (is_null($product_id)) {
            array_push($this->openAPINullablesSetToNull, 'product_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('product_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets part_id
     *
     * @return string
     */
    public function getPartId()
    {
        return $this->container['part_id'];
    }

    /**
     * Sets part_id
     *
     * @param string $part_id part_id
     *
     * @return self
     */
    public function setPartId($part_id)
    {
        if (is_null($part_id)) {
            array_push($this->openAPINullablesSetToNull, 'part_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['part_id'] = $part_id;

        return $this;
    }

    /**
     * Gets charge_id
     *
     * @return string
     */
    public function getChargeId()
    {
        return $this->container['charge_id'];
    }

    /**
     * Sets charge_id
     *
     * @param string $charge_id charge_id
     *
     * @return self
     */
    public function setChargeId($charge_id)
    {
        if (is_null($charge_id)) {
            throw new \InvalidArgumentException('non-nullable charge_id cannot be null');
        }
        $this->container['charge_id'] = $charge_id;

        return $this;
    }

    /**
     * Gets purchase_order_line_item_number
     *
     * @return string
     */
    public function getPurchaseOrderLineItemNumber()
    {
        return $this->container['purchase_order_line_item_number'];
    }

    /**
     * Sets purchase_order_line_item_number
     *
     * @param string $purchase_order_line_item_number purchase_order_line_item_number
     *
     * @return self
     */
    public function setPurchaseOrderLineItemNumber($purchase_order_line_item_number)
    {
        if (is_null($purchase_order_line_item_number)) {
            array_push($this->openAPINullablesSetToNull, 'purchase_order_line_item_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('purchase_order_line_item_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['purchase_order_line_item_number'] = $purchase_order_line_item_number;

        return $this;
    }

    /**
     * Gets ordered_quantity
     *
     * @return float
     */
    public function getOrderedQuantity()
    {
        return $this->container['ordered_quantity'];
    }

    /**
     * Sets ordered_quantity
     *
     * @param float $ordered_quantity ordered_quantity
     *
     * @return self
     */
    public function setOrderedQuantity($ordered_quantity)
    {
        if (is_null($ordered_quantity)) {
            array_push($this->openAPINullablesSetToNull, 'ordered_quantity');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ordered_quantity', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ordered_quantity'] = $ordered_quantity;

        return $this;
    }

    /**
     * Gets invoice_quantity
     *
     * @return float
     */
    public function getInvoiceQuantity()
    {
        return $this->container['invoice_quantity'];
    }

    /**
     * Sets invoice_quantity
     *
     * @param float $invoice_quantity invoice_quantity
     *
     * @return self
     */
    public function setInvoiceQuantity($invoice_quantity)
    {
        if (is_null($invoice_quantity)) {
            throw new \InvalidArgumentException('non-nullable invoice_quantity cannot be null');
        }
        $this->container['invoice_quantity'] = $invoice_quantity;

        return $this;
    }

    /**
     * Gets back_ordered_quantity
     *
     * @return float
     */
    public function getBackOrderedQuantity()
    {
        return $this->container['back_ordered_quantity'];
    }

    /**
     * Sets back_ordered_quantity
     *
     * @param float $back_ordered_quantity back_ordered_quantity
     *
     * @return self
     */
    public function setBackOrderedQuantity($back_ordered_quantity)
    {
        if (is_null($back_ordered_quantity)) {
            array_push($this->openAPINullablesSetToNull, 'back_ordered_quantity');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('back_ordered_quantity', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['back_ordered_quantity'] = $back_ordered_quantity;

        return $this;
    }

    /**
     * Gets quantity_uom
     *
     * @return string
     */
    public function getQuantityUom()
    {
        return $this->container['quantity_uom'];
    }

    /**
     * Sets quantity_uom
     *
     * @param string $quantity_uom quantity_uom
     *
     * @return self
     */
    public function setQuantityUom($quantity_uom)
    {
        if (is_null($quantity_uom)) {
            throw new \InvalidArgumentException('non-nullable quantity_uom cannot be null');
        }
        $this->container['quantity_uom'] = $quantity_uom;

        return $this;
    }

    /**
     * Gets line_item_description
     *
     * @return string
     */
    public function getLineItemDescription()
    {
        return $this->container['line_item_description'];
    }

    /**
     * Sets line_item_description
     *
     * @param string $line_item_description line_item_description
     *
     * @return self
     */
    public function setLineItemDescription($line_item_description)
    {
        if (is_null($line_item_description)) {
            throw new \InvalidArgumentException('non-nullable line_item_description cannot be null');
        }
        $this->container['line_item_description'] = $line_item_description;

        return $this;
    }

    /**
     * Gets unit_price
     *
     * @return float
     */
    public function getUnitPrice()
    {
        return $this->container['unit_price'];
    }

    /**
     * Sets unit_price
     *
     * @param float $unit_price unit_price
     *
     * @return self
     */
    public function setUnitPrice($unit_price)
    {
        if (is_null($unit_price)) {
            throw new \InvalidArgumentException('non-nullable unit_price cannot be null');
        }
        $this->container['unit_price'] = $unit_price;

        return $this;
    }

    /**
     * Gets discount_amount
     *
     * @return float
     */
    public function getDiscountAmount()
    {
        return $this->container['discount_amount'];
    }

    /**
     * Sets discount_amount
     *
     * @param float $discount_amount discount_amount
     *
     * @return self
     */
    public function setDiscountAmount($discount_amount)
    {
        if (is_null($discount_amount)) {
            array_push($this->openAPINullablesSetToNull, 'discount_amount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('discount_amount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['discount_amount'] = $discount_amount;

        return $this;
    }

    /**
     * Gets extended_price
     *
     * @return float
     */
    public function getExtendedPrice()
    {
        return $this->container['extended_price'];
    }

    /**
     * Sets extended_price
     *
     * @param float $extended_price extended_price
     *
     * @return self
     */
    public function setExtendedPrice($extended_price)
    {
        if (is_null($extended_price)) {
            throw new \InvalidArgumentException('non-nullable extended_price cannot be null');
        }
        $this->container['extended_price'] = $extended_price;

        return $this;
    }

    /**
     * Gets distributor_product_id
     *
     * @return string
     */
    public function getDistributorProductId()
    {
        return $this->container['distributor_product_id'];
    }

    /**
     * Sets distributor_product_id
     *
     * @param string $distributor_product_id distributor_product_id
     *
     * @return self
     */
    public function setDistributorProductId($distributor_product_id)
    {
        if (is_null($distributor_product_id)) {
            array_push($this->openAPINullablesSetToNull, 'distributor_product_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('distributor_product_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['distributor_product_id'] = $distributor_product_id;

        return $this;
    }

    /**
     * Gets distributor_part_id
     *
     * @return string
     */
    public function getDistributorPartId()
    {
        return $this->container['distributor_part_id'];
    }

    /**
     * Sets distributor_part_id
     *
     * @param string $distributor_part_id distributor_part_id
     *
     * @return self
     */
    public function setDistributorPartId($distributor_part_id)
    {
        if (is_null($distributor_part_id)) {
            array_push($this->openAPINullablesSetToNull, 'distributor_part_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('distributor_part_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['distributor_part_id'] = $distributor_part_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


