<?php
/**
 * Item
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Item Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Item implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Item';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'supplier_product_id' => 'string',
        'supplier_part_id' => 'string',
        'distributor_product_id' => 'string',
        'distributor_part_id' => 'string',
        'purchase_order_line_number' => 'int',
        'quantity' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'supplier_product_id' => null,
        'supplier_part_id' => null,
        'distributor_product_id' => null,
        'distributor_part_id' => null,
        'purchase_order_line_number' => null,
        'quantity' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'supplier_product_id' => true,
        'supplier_part_id' => true,
        'distributor_product_id' => true,
        'distributor_part_id' => true,
        'purchase_order_line_number' => true,
        'quantity' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'supplier_product_id' => 'supplierProductId',
        'supplier_part_id' => 'supplierPartId',
        'distributor_product_id' => 'distributorProductId',
        'distributor_part_id' => 'distributorPartId',
        'purchase_order_line_number' => 'purchaseOrderLineNumber',
        'quantity' => 'quantity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'supplier_product_id' => 'setSupplierProductId',
        'supplier_part_id' => 'setSupplierPartId',
        'distributor_product_id' => 'setDistributorProductId',
        'distributor_part_id' => 'setDistributorPartId',
        'purchase_order_line_number' => 'setPurchaseOrderLineNumber',
        'quantity' => 'setQuantity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'supplier_product_id' => 'getSupplierProductId',
        'supplier_part_id' => 'getSupplierPartId',
        'distributor_product_id' => 'getDistributorProductId',
        'distributor_part_id' => 'getDistributorPartId',
        'purchase_order_line_number' => 'getPurchaseOrderLineNumber',
        'quantity' => 'getQuantity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('supplier_product_id', $data ?? [], null);
        $this->setIfExists('supplier_part_id', $data ?? [], null);
        $this->setIfExists('distributor_product_id', $data ?? [], null);
        $this->setIfExists('distributor_part_id', $data ?? [], null);
        $this->setIfExists('purchase_order_line_number', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['supplier_product_id'] === null) {
            $invalidProperties[] = "'supplier_product_id' can't be null";
        }
        if ((mb_strlen($this->container['supplier_product_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'supplier_product_id', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['supplier_part_id'] === null) {
            $invalidProperties[] = "'supplier_part_id' can't be null";
        }
        if ((mb_strlen($this->container['supplier_part_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'supplier_part_id', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['distributor_product_id'] === null) {
            $invalidProperties[] = "'distributor_product_id' can't be null";
        }
        if ((mb_strlen($this->container['distributor_product_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'distributor_product_id', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['distributor_part_id'] === null) {
            $invalidProperties[] = "'distributor_part_id' can't be null";
        }
        if ((mb_strlen($this->container['distributor_part_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'distributor_part_id', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['purchase_order_line_number'] === null) {
            $invalidProperties[] = "'purchase_order_line_number' can't be null";
        }
        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets supplier_product_id
     *
     * @return string
     */
    public function getSupplierProductId()
    {
        return $this->container['supplier_product_id'];
    }

    /**
     * Sets supplier_product_id
     *
     * @param string $supplier_product_id supplier_product_id
     *
     * @return self
     */
    public function setSupplierProductId($supplier_product_id)
    {
        if (is_null($supplier_product_id)) {
            array_push($this->openAPINullablesSetToNull, 'supplier_product_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('supplier_product_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($supplier_product_id) && (mb_strlen($supplier_product_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $supplier_product_id when calling Item., must be smaller than or equal to 64.');
        }

        $this->container['supplier_product_id'] = $supplier_product_id;

        return $this;
    }

    /**
     * Gets supplier_part_id
     *
     * @return string
     */
    public function getSupplierPartId()
    {
        return $this->container['supplier_part_id'];
    }

    /**
     * Sets supplier_part_id
     *
     * @param string $supplier_part_id supplier_part_id
     *
     * @return self
     */
    public function setSupplierPartId($supplier_part_id)
    {
        if (is_null($supplier_part_id)) {
            array_push($this->openAPINullablesSetToNull, 'supplier_part_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('supplier_part_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($supplier_part_id) && (mb_strlen($supplier_part_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $supplier_part_id when calling Item., must be smaller than or equal to 64.');
        }

        $this->container['supplier_part_id'] = $supplier_part_id;

        return $this;
    }

    /**
     * Gets distributor_product_id
     *
     * @return string
     */
    public function getDistributorProductId()
    {
        return $this->container['distributor_product_id'];
    }

    /**
     * Sets distributor_product_id
     *
     * @param string $distributor_product_id distributor_product_id
     *
     * @return self
     */
    public function setDistributorProductId($distributor_product_id)
    {
        if (is_null($distributor_product_id)) {
            array_push($this->openAPINullablesSetToNull, 'distributor_product_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('distributor_product_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($distributor_product_id) && (mb_strlen($distributor_product_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $distributor_product_id when calling Item., must be smaller than or equal to 64.');
        }

        $this->container['distributor_product_id'] = $distributor_product_id;

        return $this;
    }

    /**
     * Gets distributor_part_id
     *
     * @return string
     */
    public function getDistributorPartId()
    {
        return $this->container['distributor_part_id'];
    }

    /**
     * Sets distributor_part_id
     *
     * @param string $distributor_part_id distributor_part_id
     *
     * @return self
     */
    public function setDistributorPartId($distributor_part_id)
    {
        if (is_null($distributor_part_id)) {
            array_push($this->openAPINullablesSetToNull, 'distributor_part_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('distributor_part_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($distributor_part_id) && (mb_strlen($distributor_part_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $distributor_part_id when calling Item., must be smaller than or equal to 64.');
        }

        $this->container['distributor_part_id'] = $distributor_part_id;

        return $this;
    }

    /**
     * Gets purchase_order_line_number
     *
     * @return int
     */
    public function getPurchaseOrderLineNumber()
    {
        return $this->container['purchase_order_line_number'];
    }

    /**
     * Sets purchase_order_line_number
     *
     * @param int $purchase_order_line_number purchase_order_line_number
     *
     * @return self
     */
    public function setPurchaseOrderLineNumber($purchase_order_line_number)
    {
        if (is_null($purchase_order_line_number)) {
            array_push($this->openAPINullablesSetToNull, 'purchase_order_line_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('purchase_order_line_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['purchase_order_line_number'] = $purchase_order_line_number;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return float
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param float $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            array_push($this->openAPINullablesSetToNull, 'quantity');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('quantity', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


