<?php
/**
 * LineType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * LineType Class Doc Comment
 *
 * @category Class
 * @description The type of order; values are enumerated: ·  “New” –A new purchase order with no prior order reference ·  “Repeat” —An exact repeat of a previous purchase order with the vendor ·  “Reference” –An order that has the same artwork as a previous order.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LineType
{
    /**
     * Possible values of this enum
     */
    public const _NEW = 'New';

    public const REPEAT = 'Repeat';

    public const REFERENCE = 'Reference';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
            self::REPEAT,
            self::REFERENCE
        ];
    }
}


