<?php
/**
 * LineItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * LineItem Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LineItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LineItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'line_number' => 'string',
        'description' => 'string',
        'line_type' => '\OpenAPI\Client\Model\LineType',
        'quantity' => '\OpenAPI\Client\Model\QuantityInput',
        'fob_id' => 'string',
        'tolerance_details' => '\OpenAPI\Client\Model\ToleranceDetails',
        'allow_partial_shipments' => 'bool',
        'unit_price' => '\OpenAPI\Client\Model\Unitprice',
        'line_item_total' => '\OpenAPI\Client\Model\Lineitemtotal',
        'requested_ship_date' => '\DateTime',
        'requested_in_hands_date' => '\DateTime',
        'reference_sales_quote' => 'string',
        'program' => '\OpenAPI\Client\Model\Program',
        'end_customer_sales_order' => 'string',
        'product_id' => 'string',
        'customer_product_id' => 'string',
        'line_item_grouping_id' => 'int',
        'part_array' => '\OpenAPI\Client\Model\PartArrayInput',
        'configuration' => '\OpenAPI\Client\Model\ConfigurationInput'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'line_number' => null,
        'description' => null,
        'line_type' => null,
        'quantity' => null,
        'fob_id' => null,
        'tolerance_details' => null,
        'allow_partial_shipments' => null,
        'unit_price' => null,
        'line_item_total' => null,
        'requested_ship_date' => 'date',
        'requested_in_hands_date' => 'date',
        'reference_sales_quote' => null,
        'program' => null,
        'end_customer_sales_order' => null,
        'product_id' => null,
        'customer_product_id' => null,
        'line_item_grouping_id' => null,
        'part_array' => null,
        'configuration' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'line_number' => false,
        'description' => false,
        'line_type' => false,
        'quantity' => true,
        'fob_id' => true,
        'tolerance_details' => false,
        'allow_partial_shipments' => false,
        'unit_price' => true,
        'line_item_total' => false,
        'requested_ship_date' => true,
        'requested_in_hands_date' => true,
        'reference_sales_quote' => true,
        'program' => true,
        'end_customer_sales_order' => true,
        'product_id' => true,
        'customer_product_id' => true,
        'line_item_grouping_id' => true,
        'part_array' => true,
        'configuration' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'line_number' => 'lineNumber',
        'description' => 'description',
        'line_type' => 'lineType',
        'quantity' => 'Quantity',
        'fob_id' => 'fobId',
        'tolerance_details' => 'ToleranceDetails',
        'allow_partial_shipments' => 'allowPartialShipments',
        'unit_price' => 'unitPrice',
        'line_item_total' => 'lineItemTotal',
        'requested_ship_date' => 'requestedShipDate',
        'requested_in_hands_date' => 'requestedInHandsDate',
        'reference_sales_quote' => 'referenceSalesQuote',
        'program' => 'Program',
        'end_customer_sales_order' => 'endCustomerSalesOrder',
        'product_id' => 'productId',
        'customer_product_id' => 'customerProductId',
        'line_item_grouping_id' => 'lineItemGroupingId',
        'part_array' => 'PartArray',
        'configuration' => 'Configuration'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'line_number' => 'setLineNumber',
        'description' => 'setDescription',
        'line_type' => 'setLineType',
        'quantity' => 'setQuantity',
        'fob_id' => 'setFobId',
        'tolerance_details' => 'setToleranceDetails',
        'allow_partial_shipments' => 'setAllowPartialShipments',
        'unit_price' => 'setUnitPrice',
        'line_item_total' => 'setLineItemTotal',
        'requested_ship_date' => 'setRequestedShipDate',
        'requested_in_hands_date' => 'setRequestedInHandsDate',
        'reference_sales_quote' => 'setReferenceSalesQuote',
        'program' => 'setProgram',
        'end_customer_sales_order' => 'setEndCustomerSalesOrder',
        'product_id' => 'setProductId',
        'customer_product_id' => 'setCustomerProductId',
        'line_item_grouping_id' => 'setLineItemGroupingId',
        'part_array' => 'setPartArray',
        'configuration' => 'setConfiguration'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'line_number' => 'getLineNumber',
        'description' => 'getDescription',
        'line_type' => 'getLineType',
        'quantity' => 'getQuantity',
        'fob_id' => 'getFobId',
        'tolerance_details' => 'getToleranceDetails',
        'allow_partial_shipments' => 'getAllowPartialShipments',
        'unit_price' => 'getUnitPrice',
        'line_item_total' => 'getLineItemTotal',
        'requested_ship_date' => 'getRequestedShipDate',
        'requested_in_hands_date' => 'getRequestedInHandsDate',
        'reference_sales_quote' => 'getReferenceSalesQuote',
        'program' => 'getProgram',
        'end_customer_sales_order' => 'getEndCustomerSalesOrder',
        'product_id' => 'getProductId',
        'customer_product_id' => 'getCustomerProductId',
        'line_item_grouping_id' => 'getLineItemGroupingId',
        'part_array' => 'getPartArray',
        'configuration' => 'getConfiguration'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('line_number', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('line_type', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('fob_id', $data ?? [], null);
        $this->setIfExists('tolerance_details', $data ?? [], null);
        $this->setIfExists('allow_partial_shipments', $data ?? [], null);
        $this->setIfExists('unit_price', $data ?? [], null);
        $this->setIfExists('line_item_total', $data ?? [], null);
        $this->setIfExists('requested_ship_date', $data ?? [], null);
        $this->setIfExists('requested_in_hands_date', $data ?? [], null);
        $this->setIfExists('reference_sales_quote', $data ?? [], null);
        $this->setIfExists('program', $data ?? [], null);
        $this->setIfExists('end_customer_sales_order', $data ?? [], null);
        $this->setIfExists('product_id', $data ?? [], null);
        $this->setIfExists('customer_product_id', $data ?? [], null);
        $this->setIfExists('line_item_grouping_id', $data ?? [], null);
        $this->setIfExists('part_array', $data ?? [], null);
        $this->setIfExists('configuration', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['line_number'] === null) {
            $invalidProperties[] = "'line_number' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['line_type'] === null) {
            $invalidProperties[] = "'line_type' can't be null";
        }
        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if ($this->container['tolerance_details'] === null) {
            $invalidProperties[] = "'tolerance_details' can't be null";
        }
        if ($this->container['allow_partial_shipments'] === null) {
            $invalidProperties[] = "'allow_partial_shipments' can't be null";
        }
        if ($this->container['unit_price'] === null) {
            $invalidProperties[] = "'unit_price' can't be null";
        }
        if ($this->container['line_item_total'] === null) {
            $invalidProperties[] = "'line_item_total' can't be null";
        }
        if ($this->container['requested_ship_date'] === null) {
            $invalidProperties[] = "'requested_ship_date' can't be null";
        }
        if ($this->container['requested_in_hands_date'] === null) {
            $invalidProperties[] = "'requested_in_hands_date' can't be null";
        }
        if ($this->container['reference_sales_quote'] === null) {
            $invalidProperties[] = "'reference_sales_quote' can't be null";
        }
        if ($this->container['program'] === null) {
            $invalidProperties[] = "'program' can't be null";
        }
        if ($this->container['end_customer_sales_order'] === null) {
            $invalidProperties[] = "'end_customer_sales_order' can't be null";
        }
        if ($this->container['product_id'] === null) {
            $invalidProperties[] = "'product_id' can't be null";
        }
        if ($this->container['customer_product_id'] === null) {
            $invalidProperties[] = "'customer_product_id' can't be null";
        }
        if ($this->container['line_item_grouping_id'] === null) {
            $invalidProperties[] = "'line_item_grouping_id' can't be null";
        }
        if ($this->container['part_array'] === null) {
            $invalidProperties[] = "'part_array' can't be null";
        }
        if ($this->container['configuration'] === null) {
            $invalidProperties[] = "'configuration' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets line_number
     *
     * @return string
     */
    public function getLineNumber()
    {
        return $this->container['line_number'];
    }

    /**
     * Sets line_number
     *
     * @param string $line_number line_number
     *
     * @return self
     */
    public function setLineNumber($line_number)
    {
        if (is_null($line_number)) {
            throw new \InvalidArgumentException('non-nullable line_number cannot be null');
        }
        $this->container['line_number'] = $line_number;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets line_type
     *
     * @return \OpenAPI\Client\Model\LineType
     */
    public function getLineType()
    {
        return $this->container['line_type'];
    }

    /**
     * Sets line_type
     *
     * @param \OpenAPI\Client\Model\LineType $line_type line_type
     *
     * @return self
     */
    public function setLineType($line_type)
    {
        if (is_null($line_type)) {
            throw new \InvalidArgumentException('non-nullable line_type cannot be null');
        }
        $this->container['line_type'] = $line_type;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return \OpenAPI\Client\Model\QuantityInput
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param \OpenAPI\Client\Model\QuantityInput $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            array_push($this->openAPINullablesSetToNull, 'quantity');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('quantity', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets fob_id
     *
     * @return string|null
     */
    public function getFobId()
    {
        return $this->container['fob_id'];
    }

    /**
     * Sets fob_id
     *
     * @param string|null $fob_id fob_id
     *
     * @return self
     */
    public function setFobId($fob_id)
    {
        if (is_null($fob_id)) {
            array_push($this->openAPINullablesSetToNull, 'fob_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fob_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fob_id'] = $fob_id;

        return $this;
    }

    /**
     * Gets tolerance_details
     *
     * @return \OpenAPI\Client\Model\ToleranceDetails
     */
    public function getToleranceDetails()
    {
        return $this->container['tolerance_details'];
    }

    /**
     * Sets tolerance_details
     *
     * @param \OpenAPI\Client\Model\ToleranceDetails $tolerance_details tolerance_details
     *
     * @return self
     */
    public function setToleranceDetails($tolerance_details)
    {
        if (is_null($tolerance_details)) {
            throw new \InvalidArgumentException('non-nullable tolerance_details cannot be null');
        }
        $this->container['tolerance_details'] = $tolerance_details;

        return $this;
    }

    /**
     * Gets allow_partial_shipments
     *
     * @return bool
     */
    public function getAllowPartialShipments()
    {
        return $this->container['allow_partial_shipments'];
    }

    /**
     * Sets allow_partial_shipments
     *
     * @param bool $allow_partial_shipments allow_partial_shipments
     *
     * @return self
     */
    public function setAllowPartialShipments($allow_partial_shipments)
    {
        if (is_null($allow_partial_shipments)) {
            throw new \InvalidArgumentException('non-nullable allow_partial_shipments cannot be null');
        }
        $this->container['allow_partial_shipments'] = $allow_partial_shipments;

        return $this;
    }

    /**
     * Gets unit_price
     *
     * @return \OpenAPI\Client\Model\Unitprice
     */
    public function getUnitPrice()
    {
        return $this->container['unit_price'];
    }

    /**
     * Sets unit_price
     *
     * @param \OpenAPI\Client\Model\Unitprice $unit_price unit_price
     *
     * @return self
     */
    public function setUnitPrice($unit_price)
    {
        if (is_null($unit_price)) {
            array_push($this->openAPINullablesSetToNull, 'unit_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('unit_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['unit_price'] = $unit_price;

        return $this;
    }

    /**
     * Gets line_item_total
     *
     * @return \OpenAPI\Client\Model\Lineitemtotal
     */
    public function getLineItemTotal()
    {
        return $this->container['line_item_total'];
    }

    /**
     * Sets line_item_total
     *
     * @param \OpenAPI\Client\Model\Lineitemtotal $line_item_total line_item_total
     *
     * @return self
     */
    public function setLineItemTotal($line_item_total)
    {
        if (is_null($line_item_total)) {
            throw new \InvalidArgumentException('non-nullable line_item_total cannot be null');
        }
        $this->container['line_item_total'] = $line_item_total;

        return $this;
    }

    /**
     * Gets requested_ship_date
     *
     * @return \DateTime
     */
    public function getRequestedShipDate()
    {
        return $this->container['requested_ship_date'];
    }

    /**
     * Sets requested_ship_date
     *
     * @param \DateTime $requested_ship_date requested_ship_date
     *
     * @return self
     */
    public function setRequestedShipDate($requested_ship_date)
    {
        if (is_null($requested_ship_date)) {
            array_push($this->openAPINullablesSetToNull, 'requested_ship_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('requested_ship_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['requested_ship_date'] = $requested_ship_date;

        return $this;
    }

    /**
     * Gets requested_in_hands_date
     *
     * @return \DateTime
     */
    public function getRequestedInHandsDate()
    {
        return $this->container['requested_in_hands_date'];
    }

    /**
     * Sets requested_in_hands_date
     *
     * @param \DateTime $requested_in_hands_date requested_in_hands_date
     *
     * @return self
     */
    public function setRequestedInHandsDate($requested_in_hands_date)
    {
        if (is_null($requested_in_hands_date)) {
            array_push($this->openAPINullablesSetToNull, 'requested_in_hands_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('requested_in_hands_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['requested_in_hands_date'] = $requested_in_hands_date;

        return $this;
    }

    /**
     * Gets reference_sales_quote
     *
     * @return string
     */
    public function getReferenceSalesQuote()
    {
        return $this->container['reference_sales_quote'];
    }

    /**
     * Sets reference_sales_quote
     *
     * @param string $reference_sales_quote reference_sales_quote
     *
     * @return self
     */
    public function setReferenceSalesQuote($reference_sales_quote)
    {
        if (is_null($reference_sales_quote)) {
            array_push($this->openAPINullablesSetToNull, 'reference_sales_quote');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reference_sales_quote', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reference_sales_quote'] = $reference_sales_quote;

        return $this;
    }

    /**
     * Gets program
     *
     * @return \OpenAPI\Client\Model\Program
     */
    public function getProgram()
    {
        return $this->container['program'];
    }

    /**
     * Sets program
     *
     * @param \OpenAPI\Client\Model\Program $program program
     *
     * @return self
     */
    public function setProgram($program)
    {
        if (is_null($program)) {
            array_push($this->openAPINullablesSetToNull, 'program');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('program', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['program'] = $program;

        return $this;
    }

    /**
     * Gets end_customer_sales_order
     *
     * @return string
     */
    public function getEndCustomerSalesOrder()
    {
        return $this->container['end_customer_sales_order'];
    }

    /**
     * Sets end_customer_sales_order
     *
     * @param string $end_customer_sales_order end_customer_sales_order
     *
     * @return self
     */
    public function setEndCustomerSalesOrder($end_customer_sales_order)
    {
        if (is_null($end_customer_sales_order)) {
            array_push($this->openAPINullablesSetToNull, 'end_customer_sales_order');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_customer_sales_order', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_customer_sales_order'] = $end_customer_sales_order;

        return $this;
    }

    /**
     * Gets product_id
     *
     * @return string
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     *
     * @param string $product_id product_id
     *
     * @return self
     */
    public function setProductId($product_id)
    {
        if (is_null($product_id)) {
            array_push($this->openAPINullablesSetToNull, 'product_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('product_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets customer_product_id
     *
     * @return string
     */
    public function getCustomerProductId()
    {
        return $this->container['customer_product_id'];
    }

    /**
     * Sets customer_product_id
     *
     * @param string $customer_product_id customer_product_id
     *
     * @return self
     */
    public function setCustomerProductId($customer_product_id)
    {
        if (is_null($customer_product_id)) {
            array_push($this->openAPINullablesSetToNull, 'customer_product_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customer_product_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customer_product_id'] = $customer_product_id;

        return $this;
    }

    /**
     * Gets line_item_grouping_id
     *
     * @return int
     */
    public function getLineItemGroupingId()
    {
        return $this->container['line_item_grouping_id'];
    }

    /**
     * Sets line_item_grouping_id
     *
     * @param int $line_item_grouping_id line_item_grouping_id
     *
     * @return self
     */
    public function setLineItemGroupingId($line_item_grouping_id)
    {
        if (is_null($line_item_grouping_id)) {
            array_push($this->openAPINullablesSetToNull, 'line_item_grouping_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('line_item_grouping_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['line_item_grouping_id'] = $line_item_grouping_id;

        return $this;
    }

    /**
     * Gets part_array
     *
     * @return \OpenAPI\Client\Model\PartArrayInput
     */
    public function getPartArray()
    {
        return $this->container['part_array'];
    }

    /**
     * Sets part_array
     *
     * @param \OpenAPI\Client\Model\PartArrayInput $part_array part_array
     *
     * @return self
     */
    public function setPartArray($part_array)
    {
        if (is_null($part_array)) {
            array_push($this->openAPINullablesSetToNull, 'part_array');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_array', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['part_array'] = $part_array;

        return $this;
    }

    /**
     * Gets configuration
     *
     * @return \OpenAPI\Client\Model\ConfigurationInput
     */
    public function getConfiguration()
    {
        return $this->container['configuration'];
    }

    /**
     * Sets configuration
     *
     * @param \OpenAPI\Client\Model\ConfigurationInput $configuration configuration
     *
     * @return self
     */
    public function setConfiguration($configuration)
    {
        if (is_null($configuration)) {
            array_push($this->openAPINullablesSetToNull, 'configuration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('configuration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['configuration'] = $configuration;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


