<?php
/**
 * PartInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PartInput Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PartInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Part-Input';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'part_group' => 'string',
        'part_id' => 'string',
        'quantity' => '\OpenAPI\Client\Model\QuantityInput',
        'customer_part_id' => 'string',
        'customer_supplied' => 'bool',
        'description' => 'string',
        'location_link_id' => 'int[]',
        'unit_price' => '\OpenAPI\Client\Model\Unitprice',
        'extended_price' => '\OpenAPI\Client\Model\Extendedprice',
        'shipment_link_array' => '\OpenAPI\Client\Model\ShipmentLinkArray'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'part_group' => null,
        'part_id' => null,
        'quantity' => null,
        'customer_part_id' => null,
        'customer_supplied' => null,
        'description' => null,
        'location_link_id' => null,
        'unit_price' => null,
        'extended_price' => null,
        'shipment_link_array' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'part_group' => true,
        'part_id' => false,
        'quantity' => false,
        'customer_part_id' => true,
        'customer_supplied' => false,
        'description' => true,
        'location_link_id' => true,
        'unit_price' => true,
        'extended_price' => true,
        'shipment_link_array' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'part_group' => 'partGroup',
        'part_id' => 'partId',
        'quantity' => 'Quantity',
        'customer_part_id' => 'customerPartId',
        'customer_supplied' => 'customerSupplied',
        'description' => 'description',
        'location_link_id' => 'locationLinkId',
        'unit_price' => 'unitPrice',
        'extended_price' => 'extendedPrice',
        'shipment_link_array' => 'ShipmentLinkArray'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'part_group' => 'setPartGroup',
        'part_id' => 'setPartId',
        'quantity' => 'setQuantity',
        'customer_part_id' => 'setCustomerPartId',
        'customer_supplied' => 'setCustomerSupplied',
        'description' => 'setDescription',
        'location_link_id' => 'setLocationLinkId',
        'unit_price' => 'setUnitPrice',
        'extended_price' => 'setExtendedPrice',
        'shipment_link_array' => 'setShipmentLinkArray'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'part_group' => 'getPartGroup',
        'part_id' => 'getPartId',
        'quantity' => 'getQuantity',
        'customer_part_id' => 'getCustomerPartId',
        'customer_supplied' => 'getCustomerSupplied',
        'description' => 'getDescription',
        'location_link_id' => 'getLocationLinkId',
        'unit_price' => 'getUnitPrice',
        'extended_price' => 'getExtendedPrice',
        'shipment_link_array' => 'getShipmentLinkArray'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('part_group', $data ?? [], null);
        $this->setIfExists('part_id', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('customer_part_id', $data ?? [], null);
        $this->setIfExists('customer_supplied', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('location_link_id', $data ?? [], null);
        $this->setIfExists('unit_price', $data ?? [], null);
        $this->setIfExists('extended_price', $data ?? [], null);
        $this->setIfExists('shipment_link_array', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['part_group'] === null) {
            $invalidProperties[] = "'part_group' can't be null";
        }
        if ($this->container['part_id'] === null) {
            $invalidProperties[] = "'part_id' can't be null";
        }
        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if ($this->container['customer_part_id'] === null) {
            $invalidProperties[] = "'customer_part_id' can't be null";
        }
        if ($this->container['customer_supplied'] === null) {
            $invalidProperties[] = "'customer_supplied' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['location_link_id'] === null) {
            $invalidProperties[] = "'location_link_id' can't be null";
        }
        if ($this->container['unit_price'] === null) {
            $invalidProperties[] = "'unit_price' can't be null";
        }
        if ($this->container['extended_price'] === null) {
            $invalidProperties[] = "'extended_price' can't be null";
        }
        if ($this->container['shipment_link_array'] === null) {
            $invalidProperties[] = "'shipment_link_array' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets part_group
     *
     * @return string
     */
    public function getPartGroup()
    {
        return $this->container['part_group'];
    }

    /**
     * Sets part_group
     *
     * @param string $part_group part_group
     *
     * @return self
     */
    public function setPartGroup($part_group)
    {
        if (is_null($part_group)) {
            array_push($this->openAPINullablesSetToNull, 'part_group');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_group', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['part_group'] = $part_group;

        return $this;
    }

    /**
     * Gets part_id
     *
     * @return string
     */
    public function getPartId()
    {
        return $this->container['part_id'];
    }

    /**
     * Sets part_id
     *
     * @param string $part_id The part Id from the supplier’s PromoStandards Product Pricing and Configuration service
     *
     * @return self
     */
    public function setPartId($part_id)
    {
        if (is_null($part_id)) {
            throw new \InvalidArgumentException('non-nullable part_id cannot be null');
        }
        $this->container['part_id'] = $part_id;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return \OpenAPI\Client\Model\QuantityInput
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param \OpenAPI\Client\Model\QuantityInput $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets customer_part_id
     *
     * @return string
     */
    public function getCustomerPartId()
    {
        return $this->container['customer_part_id'];
    }

    /**
     * Sets customer_part_id
     *
     * @param string $customer_part_id customer_part_id
     *
     * @return self
     */
    public function setCustomerPartId($customer_part_id)
    {
        if (is_null($customer_part_id)) {
            array_push($this->openAPINullablesSetToNull, 'customer_part_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customer_part_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customer_part_id'] = $customer_part_id;

        return $this;
    }

    /**
     * Gets customer_supplied
     *
     * @return bool
     */
    public function getCustomerSupplied()
    {
        return $this->container['customer_supplied'];
    }

    /**
     * Sets customer_supplied
     *
     * @param bool $customer_supplied The part will be supplied by the customer or another entity other than the supplier
     *
     * @return self
     */
    public function setCustomerSupplied($customer_supplied)
    {
        if (is_null($customer_supplied)) {
            throw new \InvalidArgumentException('non-nullable customer_supplied cannot be null');
        }
        $this->container['customer_supplied'] = $customer_supplied;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets location_link_id
     *
     * @return int[]
     */
    public function getLocationLinkId()
    {
        return $this->container['location_link_id'];
    }

    /**
     * Sets location_link_id
     *
     * @param int[] $location_link_id location_link_id
     *
     * @return self
     */
    public function setLocationLinkId($location_link_id)
    {
        if (is_null($location_link_id)) {
            array_push($this->openAPINullablesSetToNull, 'location_link_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('location_link_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['location_link_id'] = $location_link_id;

        return $this;
    }

    /**
     * Gets unit_price
     *
     * @return \OpenAPI\Client\Model\Unitprice
     */
    public function getUnitPrice()
    {
        return $this->container['unit_price'];
    }

    /**
     * Sets unit_price
     *
     * @param \OpenAPI\Client\Model\Unitprice $unit_price unit_price
     *
     * @return self
     */
    public function setUnitPrice($unit_price)
    {
        if (is_null($unit_price)) {
            array_push($this->openAPINullablesSetToNull, 'unit_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('unit_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['unit_price'] = $unit_price;

        return $this;
    }

    /**
     * Gets extended_price
     *
     * @return \OpenAPI\Client\Model\Extendedprice
     */
    public function getExtendedPrice()
    {
        return $this->container['extended_price'];
    }

    /**
     * Sets extended_price
     *
     * @param \OpenAPI\Client\Model\Extendedprice $extended_price extended_price
     *
     * @return self
     */
    public function setExtendedPrice($extended_price)
    {
        if (is_null($extended_price)) {
            array_push($this->openAPINullablesSetToNull, 'extended_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('extended_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['extended_price'] = $extended_price;

        return $this;
    }

    /**
     * Gets shipment_link_array
     *
     * @return \OpenAPI\Client\Model\ShipmentLinkArray
     */
    public function getShipmentLinkArray()
    {
        return $this->container['shipment_link_array'];
    }

    /**
     * Sets shipment_link_array
     *
     * @param \OpenAPI\Client\Model\ShipmentLinkArray $shipment_link_array shipment_link_array
     *
     * @return self
     */
    public function setShipmentLinkArray($shipment_link_array)
    {
        if (is_null($shipment_link_array)) {
            array_push($this->openAPINullablesSetToNull, 'shipment_link_array');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shipment_link_array', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shipment_link_array'] = $shipment_link_array;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


