<?php
/**
 * ProductVariationInventory
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProductVariationInventory Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProductVariationInventory implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProductVariationInventory';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'part_id' => 'string',
        'part_description' => 'string',
        'part_brand' => 'string',
        'price_variance' => 'string',
        'quantity_available' => 'string',
        'attribute_color' => 'string',
        'attribute_size' => 'string',
        'attribute_selection' => 'string',
        'attribute_flex_array' => '\OpenAPI\Client\Model\AttributeFlexArray',
        'custom_product_message' => 'string',
        'entry_type' => 'string',
        'valid_timestamp' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'part_id' => null,
        'part_description' => null,
        'part_brand' => null,
        'price_variance' => null,
        'quantity_available' => null,
        'attribute_color' => null,
        'attribute_size' => null,
        'attribute_selection' => null,
        'attribute_flex_array' => null,
        'custom_product_message' => null,
        'entry_type' => null,
        'valid_timestamp' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'part_id' => false,
        'part_description' => true,
        'part_brand' => true,
        'price_variance' => true,
        'quantity_available' => false,
        'attribute_color' => true,
        'attribute_size' => true,
        'attribute_selection' => true,
        'attribute_flex_array' => true,
        'custom_product_message' => true,
        'entry_type' => true,
        'valid_timestamp' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'part_id' => 'partID',
        'part_description' => 'partDescription',
        'part_brand' => 'partBrand',
        'price_variance' => 'priceVariance',
        'quantity_available' => 'quantityAvailable',
        'attribute_color' => 'attributeColor',
        'attribute_size' => 'attributeSize',
        'attribute_selection' => 'attributeSelection',
        'attribute_flex_array' => 'AttributeFlexArray',
        'custom_product_message' => 'customProductMessage',
        'entry_type' => 'entryType',
        'valid_timestamp' => 'validTimestamp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'part_id' => 'setPartId',
        'part_description' => 'setPartDescription',
        'part_brand' => 'setPartBrand',
        'price_variance' => 'setPriceVariance',
        'quantity_available' => 'setQuantityAvailable',
        'attribute_color' => 'setAttributeColor',
        'attribute_size' => 'setAttributeSize',
        'attribute_selection' => 'setAttributeSelection',
        'attribute_flex_array' => 'setAttributeFlexArray',
        'custom_product_message' => 'setCustomProductMessage',
        'entry_type' => 'setEntryType',
        'valid_timestamp' => 'setValidTimestamp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'part_id' => 'getPartId',
        'part_description' => 'getPartDescription',
        'part_brand' => 'getPartBrand',
        'price_variance' => 'getPriceVariance',
        'quantity_available' => 'getQuantityAvailable',
        'attribute_color' => 'getAttributeColor',
        'attribute_size' => 'getAttributeSize',
        'attribute_selection' => 'getAttributeSelection',
        'attribute_flex_array' => 'getAttributeFlexArray',
        'custom_product_message' => 'getCustomProductMessage',
        'entry_type' => 'getEntryType',
        'valid_timestamp' => 'getValidTimestamp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('part_id', $data ?? [], null);
        $this->setIfExists('part_description', $data ?? [], null);
        $this->setIfExists('part_brand', $data ?? [], null);
        $this->setIfExists('price_variance', $data ?? [], null);
        $this->setIfExists('quantity_available', $data ?? [], null);
        $this->setIfExists('attribute_color', $data ?? [], null);
        $this->setIfExists('attribute_size', $data ?? [], null);
        $this->setIfExists('attribute_selection', $data ?? [], null);
        $this->setIfExists('attribute_flex_array', $data ?? [], null);
        $this->setIfExists('custom_product_message', $data ?? [], null);
        $this->setIfExists('entry_type', $data ?? [], null);
        $this->setIfExists('valid_timestamp', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['part_id'] === null) {
            $invalidProperties[] = "'part_id' can't be null";
        }
        if ((mb_strlen($this->container['part_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'part_id', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['part_description']) && (mb_strlen($this->container['part_description']) > 256)) {
            $invalidProperties[] = "invalid value for 'part_description', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['part_brand']) && (mb_strlen($this->container['part_brand']) > 64)) {
            $invalidProperties[] = "invalid value for 'part_brand', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['price_variance']) && (mb_strlen($this->container['price_variance']) > 64)) {
            $invalidProperties[] = "invalid value for 'price_variance', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['quantity_available'] === null) {
            $invalidProperties[] = "'quantity_available' can't be null";
        }
        if ((mb_strlen($this->container['quantity_available']) > 64)) {
            $invalidProperties[] = "invalid value for 'quantity_available', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['attribute_color']) && (mb_strlen($this->container['attribute_color']) > 64)) {
            $invalidProperties[] = "invalid value for 'attribute_color', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['attribute_size']) && (mb_strlen($this->container['attribute_size']) > 64)) {
            $invalidProperties[] = "invalid value for 'attribute_size', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['attribute_selection']) && (mb_strlen($this->container['attribute_selection']) > 64)) {
            $invalidProperties[] = "invalid value for 'attribute_selection', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['custom_product_message']) && (mb_strlen($this->container['custom_product_message']) > 256)) {
            $invalidProperties[] = "invalid value for 'custom_product_message', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['entry_type']) && (mb_strlen($this->container['entry_type']) > 64)) {
            $invalidProperties[] = "invalid value for 'entry_type', the character length must be smaller than or equal to 64.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets part_id
     *
     * @return string
     */
    public function getPartId()
    {
        return $this->container['part_id'];
    }

    /**
     * Sets part_id
     *
     * @param string $part_id part_id
     *
     * @return self
     */
    public function setPartId($part_id)
    {
        if (is_null($part_id)) {
            throw new \InvalidArgumentException('non-nullable part_id cannot be null');
        }
        if ((mb_strlen($part_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $part_id when calling ProductVariationInventory., must be smaller than or equal to 64.');
        }

        $this->container['part_id'] = $part_id;

        return $this;
    }

    /**
     * Gets part_description
     *
     * @return string|null
     */
    public function getPartDescription()
    {
        return $this->container['part_description'];
    }

    /**
     * Sets part_description
     *
     * @param string|null $part_description part_description
     *
     * @return self
     */
    public function setPartDescription($part_description)
    {
        if (is_null($part_description)) {
            array_push($this->openAPINullablesSetToNull, 'part_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($part_description) && (mb_strlen($part_description) > 256)) {
            throw new \InvalidArgumentException('invalid length for $part_description when calling ProductVariationInventory., must be smaller than or equal to 256.');
        }

        $this->container['part_description'] = $part_description;

        return $this;
    }

    /**
     * Gets part_brand
     *
     * @return string|null
     */
    public function getPartBrand()
    {
        return $this->container['part_brand'];
    }

    /**
     * Sets part_brand
     *
     * @param string|null $part_brand part_brand
     *
     * @return self
     */
    public function setPartBrand($part_brand)
    {
        if (is_null($part_brand)) {
            array_push($this->openAPINullablesSetToNull, 'part_brand');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_brand', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($part_brand) && (mb_strlen($part_brand) > 64)) {
            throw new \InvalidArgumentException('invalid length for $part_brand when calling ProductVariationInventory., must be smaller than or equal to 64.');
        }

        $this->container['part_brand'] = $part_brand;

        return $this;
    }

    /**
     * Gets price_variance
     *
     * @return string|null
     */
    public function getPriceVariance()
    {
        return $this->container['price_variance'];
    }

    /**
     * Sets price_variance
     *
     * @param string|null $price_variance price_variance
     *
     * @return self
     */
    public function setPriceVariance($price_variance)
    {
        if (is_null($price_variance)) {
            array_push($this->openAPINullablesSetToNull, 'price_variance');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('price_variance', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($price_variance) && (mb_strlen($price_variance) > 64)) {
            throw new \InvalidArgumentException('invalid length for $price_variance when calling ProductVariationInventory., must be smaller than or equal to 64.');
        }

        $this->container['price_variance'] = $price_variance;

        return $this;
    }

    /**
     * Gets quantity_available
     *
     * @return string
     */
    public function getQuantityAvailable()
    {
        return $this->container['quantity_available'];
    }

    /**
     * Sets quantity_available
     *
     * @param string $quantity_available quantity_available
     *
     * @return self
     */
    public function setQuantityAvailable($quantity_available)
    {
        if (is_null($quantity_available)) {
            throw new \InvalidArgumentException('non-nullable quantity_available cannot be null');
        }
        if ((mb_strlen($quantity_available) > 64)) {
            throw new \InvalidArgumentException('invalid length for $quantity_available when calling ProductVariationInventory., must be smaller than or equal to 64.');
        }

        $this->container['quantity_available'] = $quantity_available;

        return $this;
    }

    /**
     * Gets attribute_color
     *
     * @return string|null
     */
    public function getAttributeColor()
    {
        return $this->container['attribute_color'];
    }

    /**
     * Sets attribute_color
     *
     * @param string|null $attribute_color attribute_color
     *
     * @return self
     */
    public function setAttributeColor($attribute_color)
    {
        if (is_null($attribute_color)) {
            array_push($this->openAPINullablesSetToNull, 'attribute_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('attribute_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($attribute_color) && (mb_strlen($attribute_color) > 64)) {
            throw new \InvalidArgumentException('invalid length for $attribute_color when calling ProductVariationInventory., must be smaller than or equal to 64.');
        }

        $this->container['attribute_color'] = $attribute_color;

        return $this;
    }

    /**
     * Gets attribute_size
     *
     * @return string|null
     */
    public function getAttributeSize()
    {
        return $this->container['attribute_size'];
    }

    /**
     * Sets attribute_size
     *
     * @param string|null $attribute_size attribute_size
     *
     * @return self
     */
    public function setAttributeSize($attribute_size)
    {
        if (is_null($attribute_size)) {
            array_push($this->openAPINullablesSetToNull, 'attribute_size');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('attribute_size', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($attribute_size) && (mb_strlen($attribute_size) > 64)) {
            throw new \InvalidArgumentException('invalid length for $attribute_size when calling ProductVariationInventory., must be smaller than or equal to 64.');
        }

        $this->container['attribute_size'] = $attribute_size;

        return $this;
    }

    /**
     * Gets attribute_selection
     *
     * @return string|null
     */
    public function getAttributeSelection()
    {
        return $this->container['attribute_selection'];
    }

    /**
     * Sets attribute_selection
     *
     * @param string|null $attribute_selection attribute_selection
     *
     * @return self
     */
    public function setAttributeSelection($attribute_selection)
    {
        if (is_null($attribute_selection)) {
            array_push($this->openAPINullablesSetToNull, 'attribute_selection');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('attribute_selection', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($attribute_selection) && (mb_strlen($attribute_selection) > 64)) {
            throw new \InvalidArgumentException('invalid length for $attribute_selection when calling ProductVariationInventory., must be smaller than or equal to 64.');
        }

        $this->container['attribute_selection'] = $attribute_selection;

        return $this;
    }

    /**
     * Gets attribute_flex_array
     *
     * @return \OpenAPI\Client\Model\AttributeFlexArray|null
     */
    public function getAttributeFlexArray()
    {
        return $this->container['attribute_flex_array'];
    }

    /**
     * Sets attribute_flex_array
     *
     * @param \OpenAPI\Client\Model\AttributeFlexArray|null $attribute_flex_array attribute_flex_array
     *
     * @return self
     */
    public function setAttributeFlexArray($attribute_flex_array)
    {
        if (is_null($attribute_flex_array)) {
            array_push($this->openAPINullablesSetToNull, 'attribute_flex_array');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('attribute_flex_array', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['attribute_flex_array'] = $attribute_flex_array;

        return $this;
    }

    /**
     * Gets custom_product_message
     *
     * @return string|null
     */
    public function getCustomProductMessage()
    {
        return $this->container['custom_product_message'];
    }

    /**
     * Sets custom_product_message
     *
     * @param string|null $custom_product_message custom_product_message
     *
     * @return self
     */
    public function setCustomProductMessage($custom_product_message)
    {
        if (is_null($custom_product_message)) {
            array_push($this->openAPINullablesSetToNull, 'custom_product_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_product_message', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($custom_product_message) && (mb_strlen($custom_product_message) > 256)) {
            throw new \InvalidArgumentException('invalid length for $custom_product_message when calling ProductVariationInventory., must be smaller than or equal to 256.');
        }

        $this->container['custom_product_message'] = $custom_product_message;

        return $this;
    }

    /**
     * Gets entry_type
     *
     * @return string|null
     */
    public function getEntryType()
    {
        return $this->container['entry_type'];
    }

    /**
     * Sets entry_type
     *
     * @param string|null $entry_type entry_type
     *
     * @return self
     */
    public function setEntryType($entry_type)
    {
        if (is_null($entry_type)) {
            array_push($this->openAPINullablesSetToNull, 'entry_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('entry_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($entry_type) && (mb_strlen($entry_type) > 64)) {
            throw new \InvalidArgumentException('invalid length for $entry_type when calling ProductVariationInventory., must be smaller than or equal to 64.');
        }

        $this->container['entry_type'] = $entry_type;

        return $this;
    }

    /**
     * Gets valid_timestamp
     *
     * @return \DateTime|null
     */
    public function getValidTimestamp()
    {
        return $this->container['valid_timestamp'];
    }

    /**
     * Sets valid_timestamp
     *
     * @param \DateTime|null $valid_timestamp valid_timestamp
     *
     * @return self
     */
    public function setValidTimestamp($valid_timestamp)
    {
        if (is_null($valid_timestamp)) {
            array_push($this->openAPINullablesSetToNull, 'valid_timestamp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('valid_timestamp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['valid_timestamp'] = $valid_timestamp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


