<?php
/**
 * PsdomainModelProductDataCommonFobPoint
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PsdomainModelProductDataCommonFobPoint Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PsdomainModelProductDataCommonFobPoint implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'psdomain__model__product_data__common__FobPoint';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fob_id' => 'string',
        'fob_postal_code' => 'string',
        'fob_city' => 'string',
        'fob_state' => 'string',
        'fob_country' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fob_id' => null,
        'fob_postal_code' => null,
        'fob_city' => null,
        'fob_state' => null,
        'fob_country' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'fob_id' => false,
        'fob_postal_code' => false,
        'fob_city' => true,
        'fob_state' => false,
        'fob_country' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fob_id' => 'fobId',
        'fob_postal_code' => 'fobPostalCode',
        'fob_city' => 'fobCity',
        'fob_state' => 'fobState',
        'fob_country' => 'fobCountry'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fob_id' => 'setFobId',
        'fob_postal_code' => 'setFobPostalCode',
        'fob_city' => 'setFobCity',
        'fob_state' => 'setFobState',
        'fob_country' => 'setFobCountry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fob_id' => 'getFobId',
        'fob_postal_code' => 'getFobPostalCode',
        'fob_city' => 'getFobCity',
        'fob_state' => 'getFobState',
        'fob_country' => 'getFobCountry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('fob_id', $data ?? [], null);
        $this->setIfExists('fob_postal_code', $data ?? [], null);
        $this->setIfExists('fob_city', $data ?? [], null);
        $this->setIfExists('fob_state', $data ?? [], null);
        $this->setIfExists('fob_country', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['fob_id'] === null) {
            $invalidProperties[] = "'fob_id' can't be null";
        }
        if ($this->container['fob_postal_code'] === null) {
            $invalidProperties[] = "'fob_postal_code' can't be null";
        }
        if ($this->container['fob_city'] === null) {
            $invalidProperties[] = "'fob_city' can't be null";
        }
        if ($this->container['fob_state'] === null) {
            $invalidProperties[] = "'fob_state' can't be null";
        }
        if ($this->container['fob_country'] === null) {
            $invalidProperties[] = "'fob_country' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fob_id
     *
     * @return string
     */
    public function getFobId()
    {
        return $this->container['fob_id'];
    }

    /**
     * Sets fob_id
     *
     * @param string $fob_id fob_id
     *
     * @return self
     */
    public function setFobId($fob_id)
    {
        if (is_null($fob_id)) {
            throw new \InvalidArgumentException('non-nullable fob_id cannot be null');
        }
        $this->container['fob_id'] = $fob_id;

        return $this;
    }

    /**
     * Gets fob_postal_code
     *
     * @return string
     */
    public function getFobPostalCode()
    {
        return $this->container['fob_postal_code'];
    }

    /**
     * Sets fob_postal_code
     *
     * @param string $fob_postal_code fob_postal_code
     *
     * @return self
     */
    public function setFobPostalCode($fob_postal_code)
    {
        if (is_null($fob_postal_code)) {
            throw new \InvalidArgumentException('non-nullable fob_postal_code cannot be null');
        }
        $this->container['fob_postal_code'] = $fob_postal_code;

        return $this;
    }

    /**
     * Gets fob_city
     *
     * @return string
     */
    public function getFobCity()
    {
        return $this->container['fob_city'];
    }

    /**
     * Sets fob_city
     *
     * @param string $fob_city fob_city
     *
     * @return self
     */
    public function setFobCity($fob_city)
    {
        if (is_null($fob_city)) {
            array_push($this->openAPINullablesSetToNull, 'fob_city');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fob_city', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fob_city'] = $fob_city;

        return $this;
    }

    /**
     * Gets fob_state
     *
     * @return string
     */
    public function getFobState()
    {
        return $this->container['fob_state'];
    }

    /**
     * Sets fob_state
     *
     * @param string $fob_state fob_state
     *
     * @return self
     */
    public function setFobState($fob_state)
    {
        if (is_null($fob_state)) {
            throw new \InvalidArgumentException('non-nullable fob_state cannot be null');
        }
        $this->container['fob_state'] = $fob_state;

        return $this;
    }

    /**
     * Gets fob_country
     *
     * @return string
     */
    public function getFobCountry()
    {
        return $this->container['fob_country'];
    }

    /**
     * Sets fob_country
     *
     * @param string $fob_country fob_country
     *
     * @return self
     */
    public function setFobCountry($fob_country)
    {
        if (is_null($fob_country)) {
            throw new \InvalidArgumentException('non-nullable fob_country cannot be null');
        }
        $this->container['fob_country'] = $fob_country;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


