<?php
/**
 * PsdomainModelOrderStatusV200OrderStatusDetail
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PsdomainModelOrderStatusV200OrderStatusDetail Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PsdomainModelOrderStatusV200OrderStatusDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'psdomain__model__order_status__v_2_0_0__OrderStatusDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sales_order_number' => 'string',
        'status' => 'string',
        'issue_category' => 'string',
        'expected_ship_date' => '\DateTime',
        'expected_delivery_date' => '\DateTime',
        'additional_explanation' => 'string',
        'quality_proof_url' => 'string',
        'order_contact_array' => 'Null',
        'product_array' => 'Null',
        'issue_array' => 'Null',
        'valid_timestamp' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sales_order_number' => null,
        'status' => null,
        'issue_category' => null,
        'expected_ship_date' => 'date',
        'expected_delivery_date' => 'date',
        'additional_explanation' => null,
        'quality_proof_url' => 'uri',
        'order_contact_array' => null,
        'product_array' => null,
        'issue_array' => null,
        'valid_timestamp' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'sales_order_number' => false,
        'status' => false,
        'issue_category' => true,
        'expected_ship_date' => true,
        'expected_delivery_date' => true,
        'additional_explanation' => true,
        'quality_proof_url' => true,
        'order_contact_array' => false,
        'product_array' => false,
        'issue_array' => false,
        'valid_timestamp' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sales_order_number' => 'salesOrderNumber',
        'status' => 'status',
        'issue_category' => 'issueCategory',
        'expected_ship_date' => 'expectedShipDate',
        'expected_delivery_date' => 'expectedDeliveryDate',
        'additional_explanation' => 'additionalExplanation',
        'quality_proof_url' => 'qualityProofURL',
        'order_contact_array' => 'OrderContactArray',
        'product_array' => 'ProductArray',
        'issue_array' => 'IssueArray',
        'valid_timestamp' => 'validTimestamp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sales_order_number' => 'setSalesOrderNumber',
        'status' => 'setStatus',
        'issue_category' => 'setIssueCategory',
        'expected_ship_date' => 'setExpectedShipDate',
        'expected_delivery_date' => 'setExpectedDeliveryDate',
        'additional_explanation' => 'setAdditionalExplanation',
        'quality_proof_url' => 'setQualityProofUrl',
        'order_contact_array' => 'setOrderContactArray',
        'product_array' => 'setProductArray',
        'issue_array' => 'setIssueArray',
        'valid_timestamp' => 'setValidTimestamp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sales_order_number' => 'getSalesOrderNumber',
        'status' => 'getStatus',
        'issue_category' => 'getIssueCategory',
        'expected_ship_date' => 'getExpectedShipDate',
        'expected_delivery_date' => 'getExpectedDeliveryDate',
        'additional_explanation' => 'getAdditionalExplanation',
        'quality_proof_url' => 'getQualityProofUrl',
        'order_contact_array' => 'getOrderContactArray',
        'product_array' => 'getProductArray',
        'issue_array' => 'getIssueArray',
        'valid_timestamp' => 'getValidTimestamp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('sales_order_number', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('issue_category', $data ?? [], null);
        $this->setIfExists('expected_ship_date', $data ?? [], null);
        $this->setIfExists('expected_delivery_date', $data ?? [], null);
        $this->setIfExists('additional_explanation', $data ?? [], null);
        $this->setIfExists('quality_proof_url', $data ?? [], null);
        $this->setIfExists('order_contact_array', $data ?? [], null);
        $this->setIfExists('product_array', $data ?? [], null);
        $this->setIfExists('issue_array', $data ?? [], null);
        $this->setIfExists('valid_timestamp', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['sales_order_number'] === null) {
            $invalidProperties[] = "'sales_order_number' can't be null";
        }
        if ((mb_strlen($this->container['sales_order_number']) > 64)) {
            $invalidProperties[] = "invalid value for 'sales_order_number', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ((mb_strlen($this->container['status']) > 64)) {
            $invalidProperties[] = "invalid value for 'status', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['issue_category']) && (mb_strlen($this->container['issue_category']) > 64)) {
            $invalidProperties[] = "invalid value for 'issue_category', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['additional_explanation']) && (mb_strlen($this->container['additional_explanation']) > 1024)) {
            $invalidProperties[] = "invalid value for 'additional_explanation', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['quality_proof_url']) && (mb_strlen($this->container['quality_proof_url']) > 2083)) {
            $invalidProperties[] = "invalid value for 'quality_proof_url', the character length must be smaller than or equal to 2083.";
        }

        if (!is_null($this->container['quality_proof_url']) && (mb_strlen($this->container['quality_proof_url']) < 1)) {
            $invalidProperties[] = "invalid value for 'quality_proof_url', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['valid_timestamp'] === null) {
            $invalidProperties[] = "'valid_timestamp' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sales_order_number
     *
     * @return string
     */
    public function getSalesOrderNumber()
    {
        return $this->container['sales_order_number'];
    }

    /**
     * Sets sales_order_number
     *
     * @param string $sales_order_number sales_order_number
     *
     * @return self
     */
    public function setSalesOrderNumber($sales_order_number)
    {
        if (is_null($sales_order_number)) {
            throw new \InvalidArgumentException('non-nullable sales_order_number cannot be null');
        }
        if ((mb_strlen($sales_order_number) > 64)) {
            throw new \InvalidArgumentException('invalid length for $sales_order_number when calling PsdomainModelOrderStatusV200OrderStatusDetail., must be smaller than or equal to 64.');
        }

        $this->container['sales_order_number'] = $sales_order_number;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        if ((mb_strlen($status) > 64)) {
            throw new \InvalidArgumentException('invalid length for $status when calling PsdomainModelOrderStatusV200OrderStatusDetail., must be smaller than or equal to 64.');
        }

        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets issue_category
     *
     * @return string|null
     */
    public function getIssueCategory()
    {
        return $this->container['issue_category'];
    }

    /**
     * Sets issue_category
     *
     * @param string|null $issue_category issue_category
     *
     * @return self
     */
    public function setIssueCategory($issue_category)
    {
        if (is_null($issue_category)) {
            array_push($this->openAPINullablesSetToNull, 'issue_category');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issue_category', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($issue_category) && (mb_strlen($issue_category) > 64)) {
            throw new \InvalidArgumentException('invalid length for $issue_category when calling PsdomainModelOrderStatusV200OrderStatusDetail., must be smaller than or equal to 64.');
        }

        $this->container['issue_category'] = $issue_category;

        return $this;
    }

    /**
     * Gets expected_ship_date
     *
     * @return \DateTime|null
     */
    public function getExpectedShipDate()
    {
        return $this->container['expected_ship_date'];
    }

    /**
     * Sets expected_ship_date
     *
     * @param \DateTime|null $expected_ship_date expected_ship_date
     *
     * @return self
     */
    public function setExpectedShipDate($expected_ship_date)
    {
        if (is_null($expected_ship_date)) {
            array_push($this->openAPINullablesSetToNull, 'expected_ship_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expected_ship_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expected_ship_date'] = $expected_ship_date;

        return $this;
    }

    /**
     * Gets expected_delivery_date
     *
     * @return \DateTime|null
     */
    public function getExpectedDeliveryDate()
    {
        return $this->container['expected_delivery_date'];
    }

    /**
     * Sets expected_delivery_date
     *
     * @param \DateTime|null $expected_delivery_date expected_delivery_date
     *
     * @return self
     */
    public function setExpectedDeliveryDate($expected_delivery_date)
    {
        if (is_null($expected_delivery_date)) {
            array_push($this->openAPINullablesSetToNull, 'expected_delivery_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expected_delivery_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expected_delivery_date'] = $expected_delivery_date;

        return $this;
    }

    /**
     * Gets additional_explanation
     *
     * @return string|null
     */
    public function getAdditionalExplanation()
    {
        return $this->container['additional_explanation'];
    }

    /**
     * Sets additional_explanation
     *
     * @param string|null $additional_explanation additional_explanation
     *
     * @return self
     */
    public function setAdditionalExplanation($additional_explanation)
    {
        if (is_null($additional_explanation)) {
            array_push($this->openAPINullablesSetToNull, 'additional_explanation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('additional_explanation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($additional_explanation) && (mb_strlen($additional_explanation) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $additional_explanation when calling PsdomainModelOrderStatusV200OrderStatusDetail., must be smaller than or equal to 1024.');
        }

        $this->container['additional_explanation'] = $additional_explanation;

        return $this;
    }

    /**
     * Gets quality_proof_url
     *
     * @return string|null
     */
    public function getQualityProofUrl()
    {
        return $this->container['quality_proof_url'];
    }

    /**
     * Sets quality_proof_url
     *
     * @param string|null $quality_proof_url quality_proof_url
     *
     * @return self
     */
    public function setQualityProofUrl($quality_proof_url)
    {
        if (is_null($quality_proof_url)) {
            array_push($this->openAPINullablesSetToNull, 'quality_proof_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('quality_proof_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($quality_proof_url) && (mb_strlen($quality_proof_url) > 2083)) {
            throw new \InvalidArgumentException('invalid length for $quality_proof_url when calling PsdomainModelOrderStatusV200OrderStatusDetail., must be smaller than or equal to 2083.');
        }
        if (!is_null($quality_proof_url) && (mb_strlen($quality_proof_url) < 1)) {
            throw new \InvalidArgumentException('invalid length for $quality_proof_url when calling PsdomainModelOrderStatusV200OrderStatusDetail., must be bigger than or equal to 1.');
        }

        $this->container['quality_proof_url'] = $quality_proof_url;

        return $this;
    }

    /**
     * Gets order_contact_array
     *
     * @return Null|null
     */
    public function getOrderContactArray()
    {
        return $this->container['order_contact_array'];
    }

    /**
     * Sets order_contact_array
     *
     * @param Null|null $order_contact_array order_contact_array
     *
     * @return self
     */
    public function setOrderContactArray($order_contact_array)
    {
        if (is_null($order_contact_array)) {
            throw new \InvalidArgumentException('non-nullable order_contact_array cannot be null');
        }
        $this->container['order_contact_array'] = $order_contact_array;

        return $this;
    }

    /**
     * Gets product_array
     *
     * @return Null|null
     */
    public function getProductArray()
    {
        return $this->container['product_array'];
    }

    /**
     * Sets product_array
     *
     * @param Null|null $product_array product_array
     *
     * @return self
     */
    public function setProductArray($product_array)
    {
        if (is_null($product_array)) {
            throw new \InvalidArgumentException('non-nullable product_array cannot be null');
        }
        $this->container['product_array'] = $product_array;

        return $this;
    }

    /**
     * Gets issue_array
     *
     * @return Null|null
     */
    public function getIssueArray()
    {
        return $this->container['issue_array'];
    }

    /**
     * Sets issue_array
     *
     * @param Null|null $issue_array issue_array
     *
     * @return self
     */
    public function setIssueArray($issue_array)
    {
        if (is_null($issue_array)) {
            throw new \InvalidArgumentException('non-nullable issue_array cannot be null');
        }
        $this->container['issue_array'] = $issue_array;

        return $this;
    }

    /**
     * Gets valid_timestamp
     *
     * @return \DateTime
     */
    public function getValidTimestamp()
    {
        return $this->container['valid_timestamp'];
    }

    /**
     * Sets valid_timestamp
     *
     * @param \DateTime $valid_timestamp valid_timestamp
     *
     * @return self
     */
    public function setValidTimestamp($valid_timestamp)
    {
        if (is_null($valid_timestamp)) {
            throw new \InvalidArgumentException('non-nullable valid_timestamp cannot be null');
        }
        $this->container['valid_timestamp'] = $valid_timestamp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


