<?php
/**
 * ScraperResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ScraperResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ScraperResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ScraperResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'pms_match' => 'string',
        'height' => 'string',
        'width' => 'string',
        'case_pack' => 'string',
        'case_weight' => 'string',
        'master_carton' => 'string',
        'mc_quantity' => 'string',
        'mc_price__g' => 'string',
        'mc_weight' => 'string',
        'opening_diameter' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'pms_match' => null,
        'height' => null,
        'width' => null,
        'case_pack' => null,
        'case_weight' => null,
        'master_carton' => null,
        'mc_quantity' => null,
        'mc_price__g' => null,
        'mc_weight' => null,
        'opening_diameter' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'pms_match' => true,
        'height' => true,
        'width' => true,
        'case_pack' => true,
        'case_weight' => true,
        'master_carton' => true,
        'mc_quantity' => true,
        'mc_price__g' => true,
        'mc_weight' => true,
        'opening_diameter' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'pms_match' => 'pms match',
        'height' => 'height',
        'width' => 'width',
        'case_pack' => 'case pack',
        'case_weight' => 'case weight',
        'master_carton' => 'master carton',
        'mc_quantity' => 'mc quantity',
        'mc_price__g' => 'mc price (g)',
        'mc_weight' => 'mc weight',
        'opening_diameter' => 'opening diameter'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'pms_match' => 'setPmsMatch',
        'height' => 'setHeight',
        'width' => 'setWidth',
        'case_pack' => 'setCasePack',
        'case_weight' => 'setCaseWeight',
        'master_carton' => 'setMasterCarton',
        'mc_quantity' => 'setMcQuantity',
        'mc_price__g' => 'setMcPriceG',
        'mc_weight' => 'setMcWeight',
        'opening_diameter' => 'setOpeningDiameter'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'pms_match' => 'getPmsMatch',
        'height' => 'getHeight',
        'width' => 'getWidth',
        'case_pack' => 'getCasePack',
        'case_weight' => 'getCaseWeight',
        'master_carton' => 'getMasterCarton',
        'mc_quantity' => 'getMcQuantity',
        'mc_price__g' => 'getMcPriceG',
        'mc_weight' => 'getMcWeight',
        'opening_diameter' => 'getOpeningDiameter'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('pms_match', $data ?? [], null);
        $this->setIfExists('height', $data ?? [], null);
        $this->setIfExists('width', $data ?? [], null);
        $this->setIfExists('case_pack', $data ?? [], null);
        $this->setIfExists('case_weight', $data ?? [], null);
        $this->setIfExists('master_carton', $data ?? [], null);
        $this->setIfExists('mc_quantity', $data ?? [], null);
        $this->setIfExists('mc_price__g', $data ?? [], null);
        $this->setIfExists('mc_weight', $data ?? [], null);
        $this->setIfExists('opening_diameter', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['height'] === null) {
            $invalidProperties[] = "'height' can't be null";
        }
        if ($this->container['width'] === null) {
            $invalidProperties[] = "'width' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets pms_match
     *
     * @return string|null
     */
    public function getPmsMatch()
    {
        return $this->container['pms_match'];
    }

    /**
     * Sets pms_match
     *
     * @param string|null $pms_match pms_match
     *
     * @return self
     */
    public function setPmsMatch($pms_match)
    {
        if (is_null($pms_match)) {
            array_push($this->openAPINullablesSetToNull, 'pms_match');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pms_match', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pms_match'] = $pms_match;

        return $this;
    }

    /**
     * Gets height
     *
     * @return string
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param string $height height
     *
     * @return self
     */
    public function setHeight($height)
    {
        if (is_null($height)) {
            array_push($this->openAPINullablesSetToNull, 'height');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('height', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets width
     *
     * @return string
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param string $width width
     *
     * @return self
     */
    public function setWidth($width)
    {
        if (is_null($width)) {
            array_push($this->openAPINullablesSetToNull, 'width');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('width', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets case_pack
     *
     * @return string|null
     */
    public function getCasePack()
    {
        return $this->container['case_pack'];
    }

    /**
     * Sets case_pack
     *
     * @param string|null $case_pack case_pack
     *
     * @return self
     */
    public function setCasePack($case_pack)
    {
        if (is_null($case_pack)) {
            array_push($this->openAPINullablesSetToNull, 'case_pack');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('case_pack', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['case_pack'] = $case_pack;

        return $this;
    }

    /**
     * Gets case_weight
     *
     * @return string|null
     */
    public function getCaseWeight()
    {
        return $this->container['case_weight'];
    }

    /**
     * Sets case_weight
     *
     * @param string|null $case_weight case_weight
     *
     * @return self
     */
    public function setCaseWeight($case_weight)
    {
        if (is_null($case_weight)) {
            array_push($this->openAPINullablesSetToNull, 'case_weight');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('case_weight', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['case_weight'] = $case_weight;

        return $this;
    }

    /**
     * Gets master_carton
     *
     * @return string|null
     */
    public function getMasterCarton()
    {
        return $this->container['master_carton'];
    }

    /**
     * Sets master_carton
     *
     * @param string|null $master_carton master_carton
     *
     * @return self
     */
    public function setMasterCarton($master_carton)
    {
        if (is_null($master_carton)) {
            array_push($this->openAPINullablesSetToNull, 'master_carton');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('master_carton', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['master_carton'] = $master_carton;

        return $this;
    }

    /**
     * Gets mc_quantity
     *
     * @return string|null
     */
    public function getMcQuantity()
    {
        return $this->container['mc_quantity'];
    }

    /**
     * Sets mc_quantity
     *
     * @param string|null $mc_quantity mc_quantity
     *
     * @return self
     */
    public function setMcQuantity($mc_quantity)
    {
        if (is_null($mc_quantity)) {
            array_push($this->openAPINullablesSetToNull, 'mc_quantity');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mc_quantity', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mc_quantity'] = $mc_quantity;

        return $this;
    }

    /**
     * Gets mc_price__g
     *
     * @return string|null
     */
    public function getMcPriceG()
    {
        return $this->container['mc_price__g'];
    }

    /**
     * Sets mc_price__g
     *
     * @param string|null $mc_price__g mc_price__g
     *
     * @return self
     */
    public function setMcPriceG($mc_price__g)
    {
        if (is_null($mc_price__g)) {
            array_push($this->openAPINullablesSetToNull, 'mc_price__g');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mc_price__g', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mc_price__g'] = $mc_price__g;

        return $this;
    }

    /**
     * Gets mc_weight
     *
     * @return string|null
     */
    public function getMcWeight()
    {
        return $this->container['mc_weight'];
    }

    /**
     * Sets mc_weight
     *
     * @param string|null $mc_weight mc_weight
     *
     * @return self
     */
    public function setMcWeight($mc_weight)
    {
        if (is_null($mc_weight)) {
            array_push($this->openAPINullablesSetToNull, 'mc_weight');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mc_weight', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mc_weight'] = $mc_weight;

        return $this;
    }

    /**
     * Gets opening_diameter
     *
     * @return string|null
     */
    public function getOpeningDiameter()
    {
        return $this->container['opening_diameter'];
    }

    /**
     * Sets opening_diameter
     *
     * @param string|null $opening_diameter opening_diameter
     *
     * @return self
     */
    public function setOpeningDiameter($opening_diameter)
    {
        if (is_null($opening_diameter)) {
            array_push($this->openAPINullablesSetToNull, 'opening_diameter');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('opening_diameter', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['opening_diameter'] = $opening_diameter;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


