<?php
/**
 * SpecificationType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SpecificationType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SpecificationType
{
    /**
     * Possible values of this enum
     */
    public const LENGTH = 'Length';

    public const THICKNESS = 'Thickness';

    public const RADIUS = 'Radius';

    public const VOLUME = 'Volume';

    public const CAPACITY = 'Capacity';

    public const MEMORY = 'Memory';

    public const DATA_PORTS = 'Data Ports';

    public const CAPACITANCE = 'Capacitance';

    public const VOLTAGE = 'Voltage';

    public const POINT_SIZE = 'Point Size';

    public const SHEET_SIZE = 'Sheet Size';

    public const SHEET_COUNT = 'Sheet Count';

    public const POCKETS = 'Pockets';

    public const INSEAM = 'Inseam';

    public const BUST = 'Bust';

    public const CHEST = 'Chest';

    public const WAIST = 'Waist';

    public const HIPS = 'Hips';

    public const CUP = 'Cup';

    public const RISE = 'Rise';

    public const NECK = 'Neck';

    public const THIGH = 'Thigh';

    public const SHOULDERS = 'Shoulders';

    public const SLEEVE = 'Sleeve';

    public const DEVICE_SIZE = 'Device Size';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LENGTH,
            self::THICKNESS,
            self::RADIUS,
            self::VOLUME,
            self::CAPACITY,
            self::MEMORY,
            self::DATA_PORTS,
            self::CAPACITANCE,
            self::VOLTAGE,
            self::POINT_SIZE,
            self::SHEET_SIZE,
            self::SHEET_COUNT,
            self::POCKETS,
            self::INSEAM,
            self::BUST,
            self::CHEST,
            self::WAIST,
            self::HIPS,
            self::CUP,
            self::RISE,
            self::NECK,
            self::THIGH,
            self::SHOULDERS,
            self::SLEEVE,
            self::DEVICE_SIZE
        ];
    }
}


