<?php
/**
 * ProductDataApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSRESTful Service API
 *
 * A proxy service for PromoStandards SOAP to a REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: devs@psrestful.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductDataApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductDataApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAllSellableProductIds
     *
     * Get All Sellable Product Ids.
     *
     */
    public function testGetAllSellableProductIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllSellables
     *
     * Get All Sellables.
     *
     */
    public function testGetAllSellables()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductCloseoutV100
     *
     * Get Product Closeout V100.
     *
     */
    public function testGetProductCloseoutV100()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductCloseoutV200
     *
     * Get Product Closeout V200.
     *
     */
    public function testGetProductCloseoutV200()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductDateModifiedV100
     *
     * Get Product Date Modified V100.
     *
     */
    public function testGetProductDateModifiedV100()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductDateModifiedV200
     *
     * Get Product Date Modified V200.
     *
     */
    public function testGetProductDateModifiedV200()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductSellableV100
     *
     * Get Sellables V100.
     *
     */
    public function testGetProductSellableV100()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductSellableV200
     *
     * Get Sellables V200.
     *
     */
    public function testGetProductSellableV200()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductV100
     *
     * Get Product V100.
     *
     */
    public function testGetProductV100()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductV200
     *
     * Get Product V200.
     *
     */
    public function testGetProductV200()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
